version: "3.8"

services:
    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - mystore-network    
    mystore-api:
        container_name: mystore-api
        build:
            context: ./
            dockerfile: ./Mystore/Dockerfile
        ports:
            - "5001:80"
        environment:
            - ApplicationSettings__Secret=R4ND0MLY G3N3R473D US3R S3CR37
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyStoreDatabase4;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks:
            - mystore-network
        depends_on:
            - data                   
networks:
    mystore-network:
volumes:
    sqldata: